# Generated by Django 3.2.8 on 2021-10-19 06:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_signupdoctor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('Title', models.CharField(max_length=200)),
                ('Image', models.ImageField(upload_to='')),
                ('Categories', models.CharField(max_length=50)),
                ('Summary', models.TextField()),
                ('Content', models.TextField()),
                ('Draft', models.CharField(max_length=5)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
