# Generated by Django 3.2.8 on 2021-10-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_createblog_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupdoctor',
            name='specialist',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
